# -*- coding: utf-8 -*-
"""SMART STUDY PLANNER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdZv3So2ntgYdRVf0qar5zIv7vnxUMu9
"""

import pandas as pd
from datetime import datetime,timedelta
print("===SMART STUDY PLANNER ===")
n = int(input("Enter number of subjects:"))
subjects = []
hours = []
priority = []
for i in range(n):
    print(f"\nSubject {i+1}:")
    sub = input("Enter subject name:")
    hr = float(input("Hours required:"))
    pr = int(input("Priority (1-High, 2- Medium, 3-Low):"))
    subjects.append(sub)
    hours.append(hr)
    priority.append(pr)
data = pd.DataFrame({
    "Subject": subjects,
    "Hours Required": hours,
    "Priority": priority})
data = data.sort_value(by="Priority")
print("\n===SUBJECT LIST ===")
display(data)
daily_hours = data["Hours Required"].tolist()
subject_list = data["Subject"].tolist()
day_counter = 1
while sum(remaining_hours) > 0:
     available = daily_hours
     daily_plan = []

     for i in range(len(subject_list)):
         if remaining_hours[i] > 0:
            study_time = min(remaining_hours[i], available)
            if study_time > 0:
               daily_plan.append((subject_list[i], study_time))
               remaining_hours[i] -= study_time
               available -= study_time
plan.append({"Day": f"Day {day_counter}", "Plan": daily_plan})
day_counter += 1
print("\n=== YOUR STUDY TIMETABLE ===\n")

for day in plan:
    print(day["Day"])
    for sub, hr in day["Plan"]:
        print(f"  - {sub}: {hr} hrs")
    print()

print("\n=== PROGRESS TRACKER ===")

progress = []

for sub in subject_list:
    done = float(input(f"How many hours completed for {sub}? "))
    required = data.loc[data["Subject"] == sub, "Hours Required"].values[0]
    percent = (done / required) * 100
    progress.append([sub, required, done, round(percent, 2)])

progress_df = pd.DataFrame(progress, columns=["Subject", "Total Hours", "Completed", "Progress %"])

print("\n=== CURRENT PROGRESS ===")
display(progress_df)



print("\n=== AI RECOMMENDATIONS ===")

for i, row in progress_df.iterrows():
    if row["Progress %"] < 40:
        print(f"- Spend more time on {row['Subject']} (Low progress)")
    elif 40 <= row["Progress %"] < 80:
        print(f"- You're on track in {row['Subject']}, keep going!")
    else:
        print(f"- Excellent! You are almost done with {row['Subject']}!")